name: Apply Priority Label

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - name: Extract priority from issue body
        id: extract
        run: |
          # Find the first non-empty line after "### Priority"
          PRIORITY=$(echo "${{ github.event.issue.body }}" \
            | awk '/^### Priority/{getline; while($0 ~ /^$/){getline}; print $0}' \
            | xargs)

          case "$PRIORITY" in
            High)   LABEL="Priority: HIGH" ;;
            Medium) LABEL="Priority: MEDIUM" ;;
            Low)    LABEL="Priority: LOW" ;;
            *)      LABEL="" ;;
          esac

          echo "priority=$PRIORITY"
          echo "label=$LABEL"
          echo "label=$LABEL" >> $GITHUB_OUTPUT
      - name: Add priority label
        if: steps.extract.outputs.label != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            ${{ steps.extract.outputs.label }}
