name: Update Issue Templates

on:
  workflow_call:

jobs:
  update-issue-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template: []

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all releases
        id: releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASES=$(gh release list --limit 100 --json name -q '.[].name')
          echo "Found releases:"
          echo "$RELEASES"
          echo "RELEASES<<EOF" >> $GITHUB_ENV
          echo "$RELEASES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update bug report template
        run: |
          RELEASE_OPTIONS=$(printf -- "%s\n" $RELEASES | awk '!seen[$0]++' | awk '{print "- " $0}')
          export RELEASE_OPTIONS

          yq e '
            (.body[] | select(.type == "dropdown" and .id == "version").attributes.options) = env(RELEASE_OPTIONS)
          ' -i ".github/ISSUE_TEMPLATE/${{ matrix.template }}.yml"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ".github/ISSUE_TEMPLATE/${{ matrix.template }}.yml"
          git commit -m "Update releases in issue template ${{ matrix.template }}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
